name: personal_portfolio
description: An app built using Flutter for web

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0
  flutter_bloc: ^3.2.0
  bloc: ^3.0.0
  equatable: ^1.1.1

dev_dependencies:
  pedantic: ^1.8.0

flutter:
  uses-material-design: true